name: start
version: 1.0
main: me.weecazza7.start.start
commands:
    start:
        description: A test command!
    feed:
        description: Feeds you!
    kill:
        description: Suicide
    heal:
        description: Heals you!
    tank:
        description: BOOM!
    kit:
        description: Kits!