name: start
version: 1.0
main: me.weecazza7.start.MainPvP
commands:
    kits:
        description: Lists kits
    tank:
        description: You are a tank!
    archer:
        description: Bow em up
    knight:
        description: Guard them!
    soup:
        description: Refill